// <auto-generated />
namespace EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201411130716427_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1Yy27bOBTdF5h/ELiaLmq6GaBoArlFxo4Lo3VSVJnuafHaIYakVJEK7G/rYj5pfmEu9X45kYNMB52dRd7H4T1Xh1f++/tf/vu9kt49JEZEekZeT6bEAx1GXOjdjKR2++otef/ulxf+FVd772tpd+bs0FObGbmzNr6g1IR3oJiZKBEmkYm2dhJGijIe0bPp9C19PaWAIQjG8jz/S6qtUJA94OM80iHENmVyHXGQpljHnSCL6l0zBSZmIczIHC2WIjH2ajlZMMvQ18LeEu9SCoZwApDbE7FNzx02UmXFvFeIzx5uDzFkuTGsTTlo2zRCs49waC3g0uckiiGxhy+wbbuuFsSjbXfa9a+8+64Oy4ystP3tjHjXqZRsI3Fhy6QB4sVvLgIbJfABNCTMAv/MrIUEqVq5AHiWoiYX8ZtxZTmn0zNXFsq0jiyzyHsP/zBa91DiDWyCnUS8pdgD/wR6Z+8qzGu2L1fwJ/H+0AIbD51skkLzjPlzM7dPa4IeoY1pzhL+NN5y3xV/CnG170/BXA73B1DXT74AEyYiznH+h23jlIQJZKHAVSpLG3xuG4BtN70hXh07V6FJqRnd8/dD5NUfjlE08OBBKsi1YtJcMktppUe01V+zOMYaN7S2WPGCQmhfBafrqMpj0NAMyGmFtsqEjc920NltaLwT+A1zrM+5GjB7kKAyS4en7otfl7x0cL/LFhi8bCaDt0GziEs8l0KL7IhQQTpyjxS+QcgkS45fAfNIpko/cqmMiJW/5QPR8o1+PJ92jtWtIe0VsaOXXVJGUla+F8/D2dBVMJK0Y67HK13rf7vQx+6UMdGGiGvujI/Y0txmwNbGD+6Enqp1Tarslbp1VMwvFOWEMbKUmNyEeFioe8GdvAQHY0FlPTQJvsm5FJmYlwZrpsUWjL2N/gQ3EqMCPn0Ire5sY7j8KSZR4Wrx6OTSG3dOniD1PUvCO5b8qtj+5f9uKvyXqtif5k4o46gJ7dlo6U9d3bt/1Pz10PiVv9ozwjcRws9h1mPbyOHswdlsOEM11T1xdOuLmU+bX84+8iJ2dQj3Ha0hdDTVQUubld5GJa14uiai0qTD+hos40jCZWLFloUWt0MwJhvMvzKZosmV2gBf6ZvUxqm9NAbURh6a5/Xpw/mz+bSN2b/JGs08xxEQpsAjwI3+PRWSV7iX/dfoWAjXj8W7iajwwwTD7Q5VpOtIjwxUlG8BMWjXeregYonBzI0O2D0cx/Z4DdsV8xeC7RKmmhXMV8qWZpi5kQITND3qfO6PH+r++Xn3D9h2LW0rEgAA"; }
        }
    }
}
